<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.pojobook</groupId>
        <artifactId>private-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../private-parent/pom.xml</relativePath>
    </parent>
    <artifactId>private-samples-jrecord</artifactId>
    <packaging>jar</packaging>

    <properties>
        <maven.deploy.skip>true</maven.deploy.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>net.sf</groupId>
            <artifactId>jrecord</artifactId>
            <scope>system</scope>
        </dependency>
        <dependency>
            <groupId>net.sf</groupId>
            <artifactId>jrecord-cb2xml</artifactId>
            <scope>system</scope>
        </dependency>
        <dependency>
            <groupId>org.pojobook</groupId>
            <artifactId>pojobook-core</artifactId>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
        </dependency>

        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>tools.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            
            <plugin>
                <groupId>org.pojobook</groupId>
                <artifactId>pojobook-maven-plugin</artifactId>
                <executions>
                    <!-- Generate POJOs from all copybook files -->
                    <execution>
                        <id>generate-standalone</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <copybookFile>${project.basedir}/src/test/resources/copybook/*.cbl</copybookFile>
                            <packageName>org.pojobook.samples.standalone</packageName>
                            <generatorType>standalone</generatorType>
                        </configuration>
                    </execution>
                    <execution>
                        <id>generate-annotation</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <copybookFile>${project.basedir}/src/test/resources/copybook/*.cbl</copybookFile>
                            <packageName>org.pojobook.samples.annotation</packageName>
                            <generatorType>annotation</generatorType>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>