<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.pojobook</groupId>
        <artifactId>pojobook-parent</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>private-samples-jrecord</artifactId>
    <packaging>jar</packaging>

    <properties>
        <jackson.version>2.22.0</jackson.version>
        <lombok.version>1.18.46</lombok.version>
        <lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>
        <commons-lang3.version>3.20.0</commons-lang3.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <maven-complier.version>3.8.1</maven-complier.version>
        <maven.deploy.skip>true</maven.deploy.skip>
        <jrecord.version>0.93.3</jrecord.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>net.sf</groupId>
            <artifactId>jrecord</artifactId>
            <version>${jrecord.version}</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/lib/JRecord.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>net.sf</groupId>
            <artifactId>jrecord-cb2xml</artifactId>
            <version>${jrecord.version}</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/lib/cb2xml.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.pojobook</groupId>
            <artifactId>pojobook-core</artifactId>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
        </dependency>

        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${mapstruct.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>${jackson.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${commons-lang3.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>0.2.0</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.pojobook</groupId>
                <artifactId>pojobook-maven-plugin</artifactId>
                <executions>
                    <!-- Generate POJOs from all copybook files -->
                    <execution>
                        <id>generate-standalone</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <copybookFile>${project.basedir}/src/test/resources/copybook/*.cbl</copybookFile>
                            <packageName>org.pojobook.samples.standalone</packageName>
                            <generatorType>standalone</generatorType>
                        </configuration>
                    </execution>
                    <execution>
                        <id>generate-annotation</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <copybookFile>${project.basedir}/src/test/resources/copybook/*.cbl</copybookFile>
                            <packageName>org.pojobook.samples.annotation</packageName>
                            <generatorType>annotation</generatorType>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>